import express from "express";
import cors from "cors";
import router from "./routes/router.js";
import env from "./config/env.js";
const PORT = env.PORT;
const app = express();
app.use(express.json());
app.use(cors());
app.use("/api", router);
app.listen(PORT, () => console.log("server currently running on PORT:", PORT));
