import express from "express";
import authenticationRouter from "./authentication.route.js";
import commentsRouter from "./comments.route.js";
import postRouter from "./post.route.js";
import {  mediumLimiter } from "../config/rateLimit.config.js";
import searchpostController from "../config/searchpost.controller.js";
import notificationController from "../controllers/notification.controller.js";
import verifyUser from "../utils/verifyUser.utils.js";
const router = express.Router();
router.use("/auth", authenticationRouter);
router.use("/post", postRouter);
router.use("/comment", commentsRouter);
router.get("/search", mediumLimiter, verifyUser, searchpostController);
router.get("/notifications", mediumLimiter, verifyUser, notificationController);
export default router;